#!/usr/bin/env bash
set -eo pipefail

if ! op whoami >/dev/null 2>&1; then
    echo "Please login to 1Password!"
    exit 1
fi

export GH_TOKEN=$(op read op://Gexec/Github/token)

echo "---> bot token for all repos"
gh secret set BOT_ACCESS_TOKEN --body "$(op read op://Gexec/Github/token)" --org gexec --visibility all --app actions

echo "---> bot token for .github repo (dependabot)"
gh secret set BOT_ACCESS_TOKEN --body "$(op read op://Gexec/Github/token)" --repo "gexec/.github" --app dependabot

for APP in dependabot actions; do
    echo "---> token app for public repos (${APP})"
    gh secret set TOKEN_EXCHANGE_APP --body "1130928" --org gexec --visibility all --app ${APP}

    echo "---> token install for public repos (${APP})"
    gh secret set TOKEN_EXCHANGE_INSTALL --body "60411430" --org gexec --visibility all --app ${APP}

    echo "---> token key for public repos (${APP})"
    gh secret set TOKEN_EXCHANGE_KEY --body "$(op read op://Gexec/Github/exchangekey | base64 --decode)" --org gexec --visibility all --app ${APP}

    echo "---> access key for public repos (${APP})"
    gh secret set AWS_ACCESS_KEY_ID --body "$(op read op://Gexec/Uploads/username)" --org gexec --visibility all --app ${APP}

    echo "---> secret key for public repos (${APP})"
    gh secret set AWS_SECRET_ACCESS_KEY --body "$(op read op://Gexec/Uploads/password)" --org gexec --visibility all --app ${APP}

    echo "---> gnupg key for public repos (${APP})"
    gh secret set GNUPG_KEY --body "$(op read op://Gexec/Gnupg/notesPlain)" --org gexec --visibility all --app ${APP}

    REPO=gexec-infra
    echo "---> cloudflare email for ${REPO} (${APP})"
    gh secret set CLOUDFLARE_EMAIL --body "$(op read op://Gexec/Cloudflare/username)" --repo "gexec/${REPO}" --app ${APP}

    echo "---> cloudflare token for ${REPO} (${APP})"
    gh secret set CLOUDFLARE_API_KEY --body "$(op read op://Gexec/Cloudflare/token)" --repo "gexec/${REPO}" --app ${APP}

    echo "---> access key for ${REPO} (${APP})"
    gh secret set AWS_ACCESS_KEY_ID --body "$(op read op://Gexec/Terraform/username)" --repo "gexec/${REPO}" --app ${APP}

    echo "---> secret key for ${REPO} (${APP})"
    gh secret set AWS_SECRET_ACCESS_KEY --body "$(op read op://Gexec/Terraform/password)" --repo "gexec/${REPO}" --app ${APP}

    REPO=.github
    echo "---> access key for ${REPO} (${APP})"
    gh secret set AWS_ACCESS_KEY_ID --body "$(op read op://Gexec/Terraform/username)" --repo "gexec/${REPO}" --app ${APP}

    echo "---> secret key for ${REPO} (${APP})"
    gh secret set AWS_SECRET_ACCESS_KEY --body "$(op read op://Gexec/Terraform/password)" --repo "gexec/${REPO}" --app ${APP}
done

REPO="gexec"
echo "---> codacy token for ${REPO}"
gh secret set CODACY_PROJECT_TOKEN --body "$(op read op://Gexec/Codacy/gexec)" --repo "gexec/${REPO}" --app actions

echo "---> cosign key for ${REPO}"
gh secret set COSIGN_KEY --body "$(op read op://Gexec/Cosign/notesPlain)" --repo "gexec/${REPO}" --app actions

echo "---> cosign password for ${REPO}"
gh secret set COSIGN_PASSWORD --body "$(op read op://Gexec/Cosign/Passwort)" --repo "gexec/${REPO}" --app actions

REPO="gexec-docs"
echo "---> netlify token for ${REPO}"
gh secret set NETLIFY_AUTH_TOKEN --body "$(op read op://Gexec/Netlify/token)" --repo "gexec/${REPO}" --app actions

echo "---> netlify site for ${REPO}"
gh secret set NETLIFY_SITE_ID --body b82abe27-695b-4da9-b645-b60d06a48876 --repo "gexec/${REPO}" --app actions
